# Generated by Django 3.1.4 on 2021-01-05 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bids',
            name='winner',
            field=models.BooleanField(default=False),
        ),
    ]
