# Generated by Django 3.1.4 on 2021-01-05 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_bids_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='url',
            field=models.URLField(default='http://placehold.it/460x250/e67e22/ffffff&text=HTML5'),
        ),
    ]
