# Generated by Django 3.1.4 on 2021-01-16 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0002_auto_20210115_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
