# Generated by Django 3.1.4 on 2021-01-16 04:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0003_auto_20210115_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
